In [4]:
from keras.applications.resnet50 import ResNet50
from keras.preprocessing import image
from scipy.misc import face
import numpy as np

resnet_settings = {'include_top': False, 'weights': 'imagenet'}
resnet = ResNet50(**resnet_settings)



C:\Users\yaroslav\Anaconda3\lib\site-packages\keras_applications\resnet50.py:263: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


In [15]:
resnet


In [52]:
num = np.ones(576)

In [54]:
num.shape

(576,)

In [85]:
import cv2

from PIL import Image
import glob
import cv2


frames = np.empty((10, 576, 768, 3))
cnt = -1
for img in glob.glob("train_2/*.bmp"):
        cnt = cnt + 1
        #imm = Image.open(img)
        imm = cv2.imread(img)
        x = image.img_to_array(imm)
        frames[cnt, :,:,:] = x
# какой милый енот! 
#img = img.resize((224, 224))
# в реальной жизни может понадобиться внимательнее относиться к ресайзу
        #x = image.img_to_array(imm)
       # x = np.expand_dims(x, axis=0)
# нужно дополнительное измерение, т.к. модель рассчитана на работу с массивом изображений



In [86]:
cnt

9

In [87]:
frames.shape

(10, 576, 768, 3)

In [90]:
frames[0]

array([[[46., 46., 46.],
        [43., 43., 43.],
        [39., 39., 39.],
        ...,
        [68., 68., 68.],
        [69., 69., 69.],
        [68., 68., 68.]],

       [[42., 42., 42.],
        [40., 40., 40.],
        [40., 40., 40.],
        ...,
        [66., 66., 66.],
        [69., 69., 69.],
        [66., 66., 66.]],

       [[39., 39., 39.],
        [40., 40., 40.],
        [42., 42., 42.],
        ...,
        [66., 66., 66.],
        [70., 70., 70.],
        [60., 60., 60.]],

       ...,

       [[53., 53., 53.],
        [52., 52., 52.],
        [53., 53., 53.],
        ...,
        [31., 31., 31.],
        [28., 28., 28.],
        [27., 27., 27.]],

       [[45., 45., 45.],
        [46., 46., 46.],
        [48., 48., 48.],
        ...,
        [34., 34., 34.],
        [29., 29., 29.],
        [28., 28., 28.]],

       [[42., 42., 42.],
        [42., 42., 42.],
        [47., 47., 47.],
        ...,
        [36., 36., 36.],
        [33., 33., 33.],
        [28., 28., 28.]]

In [69]:
x[0][500][700]

array([59., 59., 59.], dtype=float32)

In [91]:
features = resnet.predict(frames)

##### Массив размерности (10, 18, 24, 2048) - свернули в 32 раза несколькими слоями
##### Первая размерность 10 соответствует количеству изображений в наборе данных для обучения.
#####  (18, 24, 2048) - это размерность вектора признаков, который выдает сверточная часть сети: 2048 карт признаков размером 18х24. Можно посмотреть фрагмент вектора признаков:

In [92]:
features.shape

(10, 18, 24, 2048)

In [98]:
features[2][10][20]

array([2.091287 , 2.1851192, 0.       , ..., 0.       , 0.       ,
       0.7086047], dtype=float32)

## Теперь берем размеченное изображение (+ алгоритм Канни) 

In [104]:
image_y = cv2.imread("16_9_35_557_con2.jpg")
y = image.img_to_array(image_y)
y = np.expand_dims(y, axis=0)

In [105]:
y.shape

(1, 576, 768, 3)

In [106]:
anwers = resnet.predict(y)

In [108]:
anwers.shape

(1, 18, 24, 2048)